const ActionTypes = {
  CHANGE_GENRE: `CHANGE_GENRE`,
  LOAD_FILMS: `LOAD_FILMS`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  SIGN_IN_USER: `SIGN_IN_USER`,
  SIGN_IN_USER_ERROR: `SIGN_IN_USER_ERROR`,
  VALIDATE_SIGN_IN_USER_ERROR: `VALIDATE_SIGN_IN_USER_ERROR`,
  RESET_ERRORS: `RESET_ERRORS`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  ADD_COMMENT: `ADD_COMMENT`
};

export default ActionTypes;
