const ActionType = {
  CHANGE_GENRE: `CHANGE_GENRE`,
  LOAD_FILMS: `LOAD_FILMS`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  SIGN_IN_USER: `SIGN_IN_USER`,
  SIGN_IN_USER_ERROR: `SIGN_IN_USER_ERROR`,
  VALIDATE_SIGN_IN_USER_ERROR: `VALIDATE_SIGN_IN_USER_ERROR`,
  RESET_ERRORS: `RESET_ERRORS`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  ADD_COMMENT: `ADD_COMMENT`,
  UPDATE_FILMS: `UPDATE_FILMS`,
  LOAD_FAVORITES: `LOAD_FAVORITES`,
  LOAD_PROMO: `LOAD_PROMO`,
  INCREASE_MAX_SHOW_FILMS: `INCREASE_MAX_SHOW_FILMS`,
  TOGGLE_PLAY_BUTTON: `TOGGLE_PLAY_BUTTON`,
  RESET_MAX_SHOW_FILMS: `RESET_MAX_SHOW_FILMS`
};

export default ActionType;
